// rooms/roomsData.js
// Static room metadata module bundled with the app.
// When you add more rooms, append them here or load from a backend API.

export default {
  "CL-01": {
    id: "CL-01",
    name: "Computer Lab 1",
    description: " Proceed to the main hall, take the stairs to the second floor, second door from the stair.",
    image: require('./CL-01/Room.jpg'),
    capacity: 40,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5", "Block 6"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "IT Elective 1", instructor: "Mr. Jay Ian Camelotes" },
      { block: "Block 2", start: "09:00 AM", end: "10:00 AM", subject: "Web Information System", instructor: "Ms. Christine Joy Yap" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "IT 317", instructor: "Mrs. Aileen Concon" },
      { block: "Block 4", start: "11:00 AM", end: "12:00 PM", subject: "VB.Net Programming", instructor: "Mr. Mark Emil Dacoylo" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "Project Management", instructor: "Mrs. Arcelle Arances" },
      { block: "Block 6", start: "04:00 PM", end: "05:00 PM", subject: "ICT Trends", instructor: "Mr. Franklin Lorican" },
    ],
  },
  "CL-02": {
    id: "CL-02",
    name: "Computer Lab 2",
    description: "Proceed to the main hall, take the stairs to the second floor, and it is the last door on the left.",
    image: require('./CL-02/CL-02.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "IT 317", instructor: "Mrs. Aileen Concon" },
      { block: "Block 2", start: "09:00 AM", end: "10:00 AM", subject: "Web Information System", instructor: "Ms. Christine Joy Yap" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "IT Elective 1", instructor: "Mr. Jay Ian Camelotes" },
      { block: "Block 4", start: "11:00 AM", end: "12:00 PM", subject: "ICT Trends", instructor: "Mr. Franklin Lorican" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "VB.Net Programming", instructor: "Mr. Mark Emil Dacoylo" },
    ],
  },
  "CL-03": {
    id: "CL-03",
    name: "Computer Lab 3",
    description: "Proceed to the main hall, take the stairs to the second floor, and it is the last door on the left.",
    image: require('./CL-03/CL-03.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "VB.Net Programming", instructor: "Mr. Mark Emil Dacoylo" },
      { block: "Block 2", start: "09:00 AM", end: "10:00 AM", subject: "ICT Trends", instructor: "Mr. Franklin Lorican" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Project Management", instructor: "Mrs. Arcelie Arances" },
      { block: "Block 4", start: "11:00 AM", end: "12:00 PM", subject: "Web Information System", instructor: "Ms. Christine Joy Yap" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "IT Elective 1", instructor: "Mr. Jay Ian Camelotes" },
    ],
  },
  "CL-04": {
    id: "CL-04",
    name: "Computer Lab 4",
    description: "Proceed to the main hall, take the stairs to the second floor, and it is the last door on the left.",
    image: require('./CL04/CL-04.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "ICT Trends", instructor: "Mr. Franklin Lorican" },
      { block: "Block 2", start: "09:00 AM", end: "10:00 AM", subject: "VB.Net Programming", instructor: "Mr. Mark Emil Dacoylo" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Project Management", instructor: "Mrs. Arcelie Arances" },
      { block: "Block 4", start: "11:00 AM", end: "12:00 PM", subject: "IT 317", instructor: "Ms. Aileen Concon" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "Web Information System", instructor: "Mr. Christine Joy Yap" },
    ],
  },
  "ChemLab": {
    id: "ChemLab",
    name: "Chemistry Laboratory",
    description: "A laboratory used for experimenting, analyzing, and studying chemical substances.",
    image: require('./ChemLab/CHEMLAB.jpg'),
    capacity: 24,
    blocks: [],
    schedule: [],
  },
  "Clinic": {
    id: "Clinic",
    name: "School Clinic",
    description: "A school medical room where students can receive first aid, health assessment, and temporary medical care.",
    image: require('./Clinic/CLINIC.jpg'),
    capacity: 0,
    blocks: [],
    schedule: [],
  },
  "SpeechLab": {
    id: "SpeechLab",
    name: "Speech Laboratory",
    description: "A classroom designed to improve students’ speaking and communication skills.",
    image: require('./SpeechLab/SPEECHLAB.jpg'),
    capacity: 20,
    blocks: [],
    schedule: [],
  },
  "M-101": {
    id: "M-101",
    name: "M 101",
    description: "Second floor, last room at the far end of the hallway on the right side, near the emergency exit staircase",
    image: require('./M-101/M-101.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "Accounting Basics", instructor: "Mr. Christoff Chan" },
      { block: "Block 2", start: "02:00 AM", end: "03:00 AM", subject: "General Biology", instructor: "Mr. Van Helsing" },
      { block: "Block 3", start: "03:00 PM", end: "04:00 PM", subject: "Business Ethics", instructor: "Mr. Darko Sartoro" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "Humanities", instructor: "Ms. Clara Mendoza" },
      { block: "Block 5", start: "02:00 PM", end: "03:00 PM", subject: "Business Marketing", instructor: "Ms. Janelle Santos" },
    ],
  },
  "M-102": {
    id: "M-102",
    name: "M 102",
    description: "Second floor, third room from the right from the main staircase.",
    image: require('./M-102/M-102.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Business Math", instructor: "Mr. Rolando Poko" },
      { block: "Block 2", start: "10:00 AM", end: "11:00 AM", subject: "Quantitative Reasoning", instructor: "Mrs. Aimee Roswell" },
      { block: "Block 3", start: "01:00 PM", end: "02:00 PM", subject: "Ethics", instructor: "Mr. Maxpein Del Valle" },
      { block: "Block 4", start: "01:15 PM", end: "02:15 PM", subject: "Financial Accounting", instructor: "Mr. Joel Fernandez" },
      { block: "Block 5", start: "02:20 PM", end: "03:20 PM", subject: "Contemporary Arts", instructor: "Mr. Bryan Castillo" },
    ],
  },
  "M-103": {
    id: "M-103",
    name: "M 103",
    description: "Second floor, second room from the right after coming up the main staircase.",
    image: require('./M-103/M-103.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "02:00 AM", end: "03:00 AM", subject: "Marketing Principle", instructor: "Mr. Ace Craige" },
      { block: "Block 2", start: "03:00 AM", end: "04:00 AM", subject: "Values Education", instructor: "Mrs. Zein Shion" },
      { block: "Block 3", start: "04:00 PM", end: "05:00 PM", subject: "Algebra", instructor: "Mr. Margareth Devicay" },
      { block: "Block 4", start: "01:20 PM", end: "02:20 PM", subject: "Fundamentals of Accounting", instructor: "Mrs. Aileen Santos" },
      { block: "Block 5", start: "03:25 PM", end: "04:25 PM", subject: "Business Mathematics", instructor: "Mr. Jerome Castillo" },

    ],
  },
  "M-104": {
    id: "M-104",
    name: "M 104",
    description: "Second floor, first room from the right after coming up the main staircase.",
    image: require('./M-104/M-104.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "Business Ethics", instructor: "Mr. Ray Molse" },
      { block: "Block 2", start: "10:00 AM", end: "11:00 AM", subject: "General Biology", instructor: "Mrs. Jaja Collen" },
      { block: "Block 3", start: "01:00 PM", end: "02:00 PM", subject: "Social Science", instructor: "Mr. Jack Coal" },
      { block: "Block 4", start: "02:15 PM", end: "03:15 PM", subject: "Programming Fundamentals", instructor: "Engr. Rafael Jimenez" },
      { block: "Block 5", start: "04:10 PM", end: "05:10 PM", subject: "General Biology", instructor: "Ms. Kristine Fabella" },

    ],
  },
  "M-105": {
    id: "M-105",
    name: "M 105",
    description: "Second floor, first room from the left after coming up the main staircase.",
    image: require('./M-105/M-105.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "01:00 AM", end: "02:00 AM", subject: "Accounting Basics", instructor: "Ms. Chique Viovicente" },
      { block: "Block 2", start: "03:00 AM", end: "04:00 AM", subject: "Ethics", instructor: "Mrs. Dahlia Cajes" },
      { block: "Block 3", start: "04:00 PM", end: "05:00 PM", subject: "Quantitative Reasoning", instructor: "Mr. Ryan Greg Torreon" },
      { block: "Block 4", start: "03:05 PM", end: "04:05 PM", subject: "Social Issues & Current Events", instructor: "Dr. Regina Cortez" },
      { block: "Block 5", start: "03:45 PM", end: "04:45 PM", subject: "Introduction to Philosophy", instructor: "Sir Dominic Carreon" },

    ],
  },
  "M-106": {
    id: "M-106",
    name: "M 106",
    description: "Second floor, second room from the main staircase on the left side of the hallway.",
    image: require('./M-106/M-106.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Life Skills", instructor: "Ms. Chique Viovicente" },
      { block: "Block 2", start: "11:00 AM", end: "12:00 PM", subject: "Statistic & Probability", instructor: "Mrs. Dahlia Cajes" },
      { block: "Block 3", start: "02:00 PM", end: "03:00 PM", subject: "Environmental", instructor: "Mr. Ryan Greg Torreon" },
      { block: "Block 4", start: "01:10 PM", end: "02:10 PM", subject: "Organizational Communication", instructor: "Ms. Denise Corvera" },
      { block: "Block 5", start: "02:30 PM", end: "03:30 PM", subject: "Work Immersion Prep", instructor: "Mr. Allan Sarmiento" },

    ],
  },
  "M-107": {
    id: "M-107",
    name: "M 107",
    description: "Second floor, third room from the main staircase on the left side of the hallway.",
    image: require('./M-107/M-107.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "09:00 AM", end: "10:00 AM", subject: "Philippine History", instructor: "Mr. Ryan Greg Torreon" },
      { block: "Block 2", start: "01:00 AM", end: "02:00 AM", subject: "Algebra Review", instructor: "Mrs. Dahlia Cajes" },
      { block: "Block 3", start: "03:00 PM", end: "04:00 PM", subject: "Business Math", instructor: "Ms. Chique Viovicente" },
      { block: "Block 4", start: "02:45 PM", end: "03:45 PM", subject: "Entrepreneurship", instructor: "Mrs. Ivy De Chavez" },
      { block: "Block 5", start: "04:00 PM", end: "05:00 PM", subject: "Business Ethics", instructor: "Mr. Paulo Navarro" },

    ],
  },
  "M-108": {
    id: "M-108",
    name: "M 108",
    description: "Second floor, last room at the far end of the hallway on the left side when coming up the main staircase.",
    image: require('./M-108/M-108.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "Marketing Principles", instructor: "Ms. Chique Viovicente" },
      { block: "Block 2", start: "10:00 AM", end: "11:00 AM", subject: "Mathematics in the Modern World", instructor: "Mr. Ryan Greg Torreon" },
      { block: "Block 3", start: "11:00 AM", end: "12:00 PM", subject: "Physics", instructor: "Mr. Edison Alcazar" },
      { block: "Block 4", start: "03:15 PM", end: "04:15 PM", subject: "Research in Daily Life", instructor: "Mrs. Anna Labrador" },
      { block: "Block 5", start: "03:30 PM", end: "04:30 PM", subject: "Physical Science", instructor: "Mr. Roderick Ventura" },

    ],
  },
  "M-109": {
    id: "M-109",
    name: "M 109",
    description: "First floor, near the back hallway.",
    image: require('./M-109/M-109.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "PE Lecture", instructor: "Coach Villamor" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Health Education", instructor: "Ms. Catanghal" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Life Skills", instructor: "Ms. Bayot" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Homeroom Guidance", instructor: "Mr. Quijano" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "Study & Career Pathways", instructor: "Ms. Requilme" },
    ],
  },
  "M-201": {
    id: "M-201",
    name: "M 201",
    description: "Second floor, first room after the stairs.",
    image: require('./M-201/M-201.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Mathematics in the Modern World", instructor: "Ms. Manigo" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Statistics & Probability", instructor: "Mr. Villar" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Algebra Review", instructor: "Ms. Tabigue" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Quantitative Reasoning", instructor: "Mr. Sevilla" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "Logic & Problem Solving", instructor: "Ms. Layson" },
    ],
  },
  "M-202": {
    id: "M-202",
    name: "M 202",
    description: "Second floor, near the center staircase.",
    image: require('./M-202/M-202.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Business Math", instructor: "Ms. Lloren" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Entrepreneurship", instructor: "Mr. Cabanilla" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Marketing Principles", instructor: "Ms. Paglinawan" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Business Ethics", instructor: "Mr. Ledesma" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "Accounting Basics", instructor: "Ms. Petalio" },
    ],
  },
  "M-203": {
    id: "M-203",
    name: "M 203",
    description: "Second floor, middle section of the corridor.",
    image: require('./M-203/M-203.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Philippine History", instructor: "Mr. Cabahug" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Social Science", instructor: "Ms. Daligdig" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Values Education", instructor: "Fr. Ramirez" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Ethics", instructor: "Mr. Bautista" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "NSTP Lecture", instructor: "Ms. Amora" },
    ],
  },
  "M-204": {
    id: "M-204",
    name: "M 204",
    description: "Second floor, same hallway as M-205, left side.",
    image: require('./M-204/M-204.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "General Biology", instructor: "Ms. Abapo" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Earth Science", instructor: "Mr. Tampus" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Environmental Science", instructor: "Ms. Cabanag" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Research 1", instructor: "Ms. Almazan" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "Disaster Readiness", instructor: "Mr. Fiel" },
    ],
  },
  "M-205": {
    id: "M-205",
    name: "M 205",
    description: "Second floor, right-wing, beside M-206.",
    image: require('./M-205/M-205.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Oral Communication", instructor: "Ms. Gamboa" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Purposive Communication", instructor: "Mr. Diola" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "English Grammar", instructor: "Ms. Lazo" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Reading & Writing Skills", instructor: "Ms. Franco" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "Speech Practice", instructor: "Mr. Ocampo" },
    ],
  },
  "M-206": {
    id: "M-206",
    name: "M 206",
    description: "Second floor, right-wing hallway, near the stair landing.",
    image: require('./M-206/M-206.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Programming 1", instructor: "Mr. Reyes" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Data Structures", instructor: "Ms. Perez" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Computer Literacy", instructor: "Ms. Velasco" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Systems Analysis", instructor: "Mr. Santiago" },
      { block: "Block 5", start: "11:00 AM", end: "12:00 PM", subject: "ICT Applications", instructor: "Ms. Navarro" },
    ],
  },
  "M-207": {
    id: "M-207",
    name: "M 207",
    description: "Back of the main hall; turn right.",
    image: require('./M-207/M-207.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "09:00 AM", end: "10:00 AM", subject: "Environmental Science", instructor: "Mrs. Chique Viovicente" },
      { block: "Block 2", start: "02:00 PM", end: "03:00 PM", subject: "Entrepreneurial Mind", instructor: "Mrs. Danica Alesna" },
      { block: "Block 3", start: "04:00 PM", end: "05:00 PM", subject: "Foreign Language", instructor: "Angel Curato" },
    ],
  },
  "M-208": {
    id: "M-208",
    name: "M 208",
    description: "Back of the main hall; turn right.",
    image: require('./M-208/M-208.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "12:00 AM", end: "01:00 AM", subject: "Environmental Science", instructor: "Mrs. Chique Viovicente" },
      { block: "Block 2", start: "01:00 PM", end: "02:00 PM", subject: "Computer Mediated Communication", instructor: "Mr. Ryan Greg Torreon" },
      { block: "Block 3", start: "03:00 PM", end: "04:00 PM", subject: "Tech Write", instructor: "Mrs. Angelica Devicay" },
    ],
  },
  "M-209": {
    id: "M-209",
    name: "M 209",
    description: "Main hall, then turn left.",
    image: require('./M-209/M-209.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:00 AM", subject: "Tech Write", instructor: "Mrs. Angelica Devicay" },
      { block: "Block 2", start: "10:00 AM", end: "11:00 AM", subject: "System Analyst & Design", instructor: "Mrs. Vernaliza Magdadaro" },
      { block: "Block 3", start: "12:00 PM", end: "01:00 PM", subject: "Foreign Language", instructor: "Angel Curato" },
    ],
  },
  "E-101": {
    id: "E-101",
    name: "E 101",
    description: "Go to the extension room, you’ll see the first door on the left.",
    image: require('./E-101/E-101.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Computer Concepts", instructor: "Mrs. Mercy Cutanda" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Purposive Communication", instructor: "Ms. Danica Reyes" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Computer Programming 1", instructor: "Mr. Julius Ortega" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "PE 1 – Physical Fitness", instructor: "Mrs. Elaine Santiago" },
      { block: "Block 5", start: "03:00 PM", end: "04:00 PM", subject: "Ethics", instructor: "Mr. Carlo Mendoza" },
    ],
  },
  "E-102": {
    id: "E-102",
    name: "E 102",
    description: "Proceed to second room in the left.",
    image: require('./E-102/E-102.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Computer Concepts", instructor: "Mrs. Mercy Cutanda" },
      { block: "Block 2", start: "09:00 AM", end: "10:00 AM", subject: "Discrete Mathematics", instructor: "Ms. Kristine Bautista" },
      { block: "Block 3", start: "10:00 AM", end: "11:50 AM", subject: "Computer Programming 1", instructor: "Mr. Jomar Dela Cruz" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "Fundamentals of Database", instructor: "Mrs. Angelica Torres" },
      { block: "Block 5", start: "02:00 PM", end: "03:00 PM", subject: "Ethics", instructor: "Mr. Raymond Valdez" },
    ],
  },
  "E-103": {
    id: "E-103",
    name: "E 103",
    description: "Room E-103, beside Room E-102.",
    image: require('./E-103/E-103.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "08:00 AM", end: "09:30 AM", subject: "Data Structures and Algorithms", instructor: "Mr. Miguel Soriano" },
      { block: "Block 2", start: "09:30 AM", end: "10:20 AM", subject: "Human–Computer Interaction", instructor: "Ms. Cherry De Leon" },
      { block: "Block 3", start: "10:20 AM", end: "11:00 AM", subject: "Fundamentals of Database System", instructor: "Mrs. Angelica Torres" },
      { block: "Block 4", start: "12:00 PM", end: "01:00 PM", subject: "PE 2 – Physical Fitness", instructor: "Mrs. Elaine Santiago" },
      { block: "Block 5", start: "04:00 PM", end: "05:00 PM", subject: "Ethics", instructor: "Mr. Carlo Mendoza" },
    ],
  },
  "E-104": {
    id: "E-104",
    name: "E 104",
    description: "Room 104, third door on the right.",
    image: require('./E-104/E-104.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Basic Accounting", instructor: "Ms. Rhianne Lopez" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "General Biology", instructor: "Mr. Paolo Villanueva" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Introduction to Criminology", instructor: "Mr. Brian Cortez" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "PE 1 – Physical Fitness", instructor: "Mr. Carlo Aquino" },
      { block: "Block 5", start: "03:00 PM", end: "04:00 PM", subject: "Business Math", instructor: "Ms. Trisha Gomez" },
    ],
  },
  "E-105": {
    id: "E-105",
    name: "E 105",
    description: "Proceed to Room E-105, beside Room E-104.",
    image: require('./E-105/E-105.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Tourism Planning & Development", instructor: "Ms. Alyssa Duran" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Educational Psychology", instructor: "Ms. Cherry Lao" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Thermodynamics (Engineering)", instructor: "Mr. Patrick Salazar" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "Fundamentals of Nursing", instructor: "Mrs. Rina Fernandez" },
      { block: "Block 5", start: "03:00 PM", end: "04:00 PM", subject: "Platform Technologies", instructor: "Mr. Tristan Ramos" },
    ],
  },
  "E-201": {
    id: "E-201",
    name: "E 201",
    description: "Proceed to Room E-201, beside Room E-202.",
    image: require('./E-201/E-201.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Introduction to Sociology", instructor: "Ms. Maria Santos" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Financial Accounting", instructor: "Mr. John Dela Cruz" },
      { block: "Block 3", start: "10:00 AM", end: "11:00 AM", subject: "Microbiology", instructor: "Mrs. Angela Reyes" },
      { block: "Block 4", start: "01:00 PM", end: "02:00 PM", subject: "PE 1 – Physical Fitness", instructor: "Mr. Carlo Aquino" },
      { block: "Block 5", start: "03:00 PM", end: "04:00 PM", subject: "Ethics", instructor: "Ms. Trisha Gomez" },
    ],
  },
  "E-202": {
    id: "E-202",
    name: "E 202",
    description: "Proceed to Room E-202, beside Room E-203.",
    image: require('./E-202/E-202.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Computer Programming 1", instructor: "Mr. Julius Ortega" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Purposive Communication", instructor: "Ms. Danica Reyes" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "General Biology", instructor: "Mr. Paolo Villanueva" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Art Appreciation", instructor: "Ms. Julia Mendoza" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "Business Math", instructor: "Ms. Trisha Gomez" },
    ],
  },
  "E-203": {
    id: "E-203",
    name: "E 203",
    description: "Proceed to Room E-203, beside Room E-204.",
    image: require('./E-203/E-203.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Introduction to Philosophy", instructor: "Mr. Jerome Santos" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Financial Accounting", instructor: "Mr. Ohn Dela Cruz" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Microbiology", instructor: "Mrs. Angela Reyes" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Educational Psychology", instructor: "Ms. Cherry Lao" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "Marketing Management", instructor: "Ms. Alyssa Duran" },
    ],
  },
  "E-204": {
    id: "E-204",
    name: "E 204",
    description: "Proceed to Room E-204, beside Room E-205.",
    image: require('./E-204/E-204.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Introduction to Philosophy", instructor: "Mr. Jerome Santos" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Financial Accounting", instructor: "Mr. John Dela Cruz" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Microbiology", instructor: "Mrs. Angela Reyes" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "Educational Psychology", instructor: "Ms. Cherry Lao" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "Marketing Management", instructor: "Ms. Alyssa Durano" },
    ],
  },
  "E-205": {
    id: "E-205",
    name: "E 205",
    description: "Room E-205 — the next room in the hallway.",
    image: require('./E-205/E-205.jpg'),
    capacity: 30,
    blocks: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    schedule: [
      { block: "Block 1", start: "07:00 AM", end: "08:00 AM", subject: "Tourism Planning & Development", instructor: "Ms. Alyssa Duran" },
      { block: "Block 2", start: "08:00 AM", end: "09:00 AM", subject: "Anatomy & Physiology", instructor: "Mrs. Rina Fernandez" },
      { block: "Block 3", start: "09:00 AM", end: "10:00 AM", subject: "Introduction to Criminology", instructor: "Mr. Brian Cortez" },
      { block: "Block 4", start: "10:00 AM", end: "11:00 AM", subject: "General Biology", instructor: "Mr. Paolo Villanueva" },
      { block: "Block 5", start: "01:00 PM", end: "02:00 PM", subject: "PE 1 – Physical Fitness", instructor: "Mr. Carlo Aquino" },
    ],
  },
};
